
CREATE EXTENSION IF NOT EXISTS "pgcrypto";


CREATE TABLE recovery_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT NOT NULL,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  expire_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP + INTERVAL '15 minutes') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
